export const cvxToVaxTradename = {
  "207": "Moderna Spikevax COVID-19 mRNA",
  "208": "Pfizer-BioNTech Comirnaty COVID-19 mRNA",
  "210": "AstraZeneca Vaxzevria COVID-19",
  "212": "Janssen Johnson & Johnson COVID-19",
  "501": "QazCovid-in COVID-19",
  "502": "COVAXIN COVID-19",
  "503": "CoviVac COVID-19",
  "504": "Sputnik Light COVID-19",
  "505": "Sputnik V COVID-19",
  "509": "EpiVacCorona COVID-19",
  "510": "SINOPHARM-BIBP COVID-19",
  "511": "CoronaVac COVID-19"
}

export const mvxToCompanyName = {
  "AB": "Abbott Laboratories",
  "ACA": "Acambis, Inc",
  "AD": "Adams Laboratories, Inc.",
  "ALP": "Alpha Therapeutic Corporation",
  "AR": "Armour",
  "AVB": "Aventis Behring L.L.C.",
  "AVI": "Aviron",
  "BA": "Baxter Healthcare Corporation-inactive",
  "BAH": "Baxter Healthcare Corporation",
  "BAY": "Bayer Corporation",
  "BP": "Berna Products",
  "BPC": "Berna Products Corporation",
  "BTP": "Biotest Pharmaceuticals Corporation",
  "MIP": "Emergent BioSolutions",
  "CSL": "bioCSL",
  "CNJ": "Cangene Corporation",
  "CMP": "Celltech Medeva Pharmaceuticals",
  "CEN": "Centeon L.L.C.",
  "CHI": "Chiron Corporation",
  "CON": "Connaught",
  "DVC": "DynPort Vaccine Company, LLC",
  "EVN": "Evans Medical Limited",
  "GEO": "GeoVax Labs, Inc.",
  "SKB": "GlaxoSmithKline",
  "GRE": "Greer Laboratories, Inc.",
  "IAG": "Immuno International AG",
  "IUS": "Immuno-U.S., Inc.",
  "INT": "Intercell Biomedical",
  "KGC": "Korea Green Cross Corporation",
  "LED": "Lederle",
  "MBL": "Massachusetts Biologic Laboratories",
  "MA": "Massachusetts Public Health Biologic Laboratories",
  "MED": "MedImmune, Inc. (AstraZeneca)",
  "MSD": "Merck and Co., Inc.",
  "IM": "Merieux",
  "MIL": "Miles",
  "NAB": "NABI",
  "NYB": "New York Blood Center",
  "NAV": "North American Vaccine, Inc.",
  "NOV": "Novartis Pharmaceutical Corporation",
  "NVX": "Novavax, Inc.",
  "OTC": "Organon Teknika Corporation",
  "ORT": "Ortho-clinical Diagnostics",
  "PD": "Parkedale Pharmaceuticals",
  "PWJ": "PowderJect Pharmaceuticals",
  "PRX": "Praxis Biologics",
  "JPN": "The Research Foundation for Microbial Diseases of Osaka University (BIKEN)",
  "PMC": "Sanofi Pasteur",
  "SCL": "Sclavo, Inc.",
  "SOL": "Solvay Pharmaceuticals",
  "SI": "Swiss Serum and Vaccine Inst.",
  "TAL": "Talecris Biotherapeutics",
  "USA": "United States Army Medical Research and Material Command",
  "VXG": "VaxGen",
  "WA": "Wyeth-Ayerst",
  "WAL": "Wyeth",
  "ZLB": "ZLB Behring",
  "OTH": "Other manufacturer",
  "UNK": "Unknown manufacturer",
  "AKR": "Akorn, Inc",
  "PFR": "Pfizer, Inc",
  "BRR": "Barr Laboratories",
  "JNJ": "Johnson and Johnson",
  "PSC": "Protein Sciences",
  "IDB": "ID Biomedical",
  "GRF": "Grifols",
  "CRU": "Crucell",
  "KED": "Kedrion Biopharma",
  "PAX": "Emergent Travel Health, Inc (Formerly PaxVax)",
  "MCM": "MCM Vaccine Company",
  "SEQ": "Seqirus",
  "VAL": "Valneva",
  "DYN": "Dynaport",
  "DVX": "Dynavax, Inc.",
  "DSI": "Dispensing Solutions",
  "REB": "Rebel Distributors",
  "VET": "Vetter Pharma Fertigung GmbH & Co. KG",
  "TVA": "TEVA Pharmaceuticals USA ",
  "BN": "Bavarian Nordic A/S",
  "MOD": "Moderna US, Inc.",
  "ASZ": "AstraZeneca",
  "JSN": "Janssen",
  "SPH": "Sinopharm-Biotech",
  "SNV": "Sinovac ",
  "MSP": "MSP Vaccine Company - (partnership Merck and Sanofi Pasteur)",
  "BBI": "Bharat Biotech International Limited"
}